name: Build Using arduino-cli

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update system and install build tool
        run: |
          sudo apt-get update -y
          wget -qO arduino-cli.tar.gz https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          sudo tar xf arduino-cli.tar.gz
          rm -rf arduino-cli.tar.gz
          sudo chmod u+x ./arduino-cli
          ./arduino-cli --help

      - name: arduino-cli install boards [build dependencies]
        run: |
          ./arduino-cli core update-index
          ./arduino-cli config init
          ./arduino-cli config add board_manager.additional_urls http://drazzy.com/package_drazzy.com_index.json
          ./arduino-cli config set library.enable_unsafe_install true
          ./arduino-cli core update-index
          ./arduino-cli config dump
          ls -l
          ./arduino-cli core install megaTinyCore:megaavr
          ./arduino-cli core upgrade
          ./arduino-cli core update-index

      - name: arduino-cli install libraries [build dependencies]
        run: |
          ./arduino-cli lib install TinyMegaI2C
          ./arduino-cli lib install RV8803Tiny

      - name: compile binary
        run: |
          rm -rf build
          ls -l
          cp clock_firmware_production.ino watch_firmware.ino
          ls -l
          FQBN_ARG="-b megaTinyCore:megaavr:atxy7:chip=1607,clock=5internal,bodvoltage=1v8,bodmode=disabled,eesave=enable,millis=enabled,resetpin=UPDI,startuptime=0,wiremode=mors,printf=minimal,attach=allenabled"
          OUTPUT_ARG="--output-dir $(pwd)/build"
          ./arduino-cli compile $FQBN_ARG $OUTPUT_ARG
          ls -l
          rm watch_firmware.ino

