name: Build Using arduino-cli

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # download and install arduino-cli binary 
      - name: update system and install build tool
        run: |
          sudo apt-get update -y
          wget -qO arduino-cli.tar.gz https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          sudo tar xf arduino-cli.tar.gz
          rm -rf arduino-cli.tar.gz
          sudo chmod u+x ./arduino-cli
          ./arduino-cli --help

      # 1. Create config file used by arduino-cli
      # 2. Add our board donwload uri in there
      # 3. Set a flag in that config file to download libs from git uris
      # 4. Update the core-index(which downloads automatically and updates arduino-cli's dependencies)
      # 5. Install our boards (i.e. uCs)
      - name: arduino-cli install boards [build dependencies]
        run: |
          ./arduino-cli core update-index
          ./arduino-cli config init
          ./arduino-cli config add board_manager.additional_urls http://drazzy.com/package_drazzy.com_index.json
          ./arduino-cli config set library.enable_unsafe_install true
          ./arduino-cli core update-index
          ./arduino-cli config dump
          ls -l
          ./arduino-cli core install megaTinyCore:megaavr
          ./arduino-cli core upgrade
          ./arduino-cli core update-index

      # Install the libraries 
      - name: arduino-cli install libraries [build dependencies]
        run: |
          ./arduino-cli lib install TinyMegaI2C
          ./arduino-cli lib install RV8803Tiny

      # Clean compile the code in build directory
      # Gotcha: The main Arduino ino file is named differently than the repo name. 
      # So we had to do some renaming as the compiler follows traditional arduino paradigm,
      # where the main ino file should have the same prefix name as the src root directory. 
      - name: compile binary [clean build in /build/ dir]
        run: |
          rm -rf build
          mv clock_firmware_production.ino watch_firmware.ino
          FQBN_ARG="-b megaTinyCore:megaavr:atxy7:chip=1607,clock=5internal,bodvoltage=1v8,bodmode=disabled,eesave=enable,millis=enabled,resetpin=UPDI,startuptime=0,wiremode=mors,printf=default,attach=allenabled"
          OUTPUT_ARG="--output-dir $(pwd)/build"
          ./arduino-cli compile $FQBN_ARG $OUTPUT_ARG
          mv watch_firmware.ino clock_firmware_production.ino 
          cd build
          for f in watch_firmware*; do mv "$f" "clock_firmware_production${f#watch_firmware}"; done
          ls -l
          cd ..

