name: Build Uisng arduino-cli

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          sudo apt-get install wget tar curl  -y
          wget -qO https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          sudo tar xf arduino-cli.tar.gz
          ls -l

      - name: create arduino-cli definition file
        run: |
          echo create definition

      - name: install libraries
        run: |
          echo install libraries

      - name: compile binary
        run: |
          echo compile binary
