name: Build Using arduino-cli

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          wget -qO arduino-cli.tar.gz https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          sudo tar xf arduino-cli.tar.gz
          rm -rf arduino-cli.tar.gz
          sudo chmod u+x ./arduino-cli
          ./arduino-cli --help

      - name: arduino-cli install boards
        run: |
          ./arduino-cli core update-index
          ./arduino-cli config init
          ./arduino-cli config add board_manager.additional_urls http://drazzy.com/package_drazzy.com_index.json
          ./arduino-cli config set library.enable_unsafe_install true
          ./arduino-cli core update-index
          ./arduino-cli config dump
          ls -l

      - name: arduino-cli install libraries
        run: |
          echo install libraries

      - name: compile binary
        run: |
          echo compile binary
