name: create release

# Triggers the workflow on new release push
on:
  push:
    branches:
      - production
      - release_bin
      - 'release/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Build Binary packages (interested in .hex)
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Executed successfully, when pushed on release branch