name: File name pre-ext from tag test


on:
  push:
    tags:        
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: GBet tage name and add to file name before ext
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag version
        run: |
          sudo apt-get update -y
          clear

          echo "TAG: ${{github.ref_name}}"