name: File name pre-ext from tag test


on:
  push:
    tags:        
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Get tag name and add to file name before ext
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag ver
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Read tag ver
        run: |
          TAG="`echo $(git describe --tags --abbrev=0)`"
          TAG_NOT_V="`echo $TAG | sed 's/v//g'`"
          TAG_NOT_DOT="`echo $TAG_NOT_V | sed 's/\./_/g'`"
          echo $TAG_NOT_DOT
