name: Push to AWS S3 on new release on github

# Triggers the workflow on new release's publish
on:
  release:
    types: [published]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: upload binary files from (.hex) to AWS S3 as well
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Executed successfully, when pushed on release branch
