name: Tagged-release

on:
  # push:
  #   tags:        
  #     - 'v*'
  workflow_dispatch:

jobs:
  build_and_upload_release:
    name: build_and_upload_release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        

      - name: create release artifact
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: set hex file's name and path as env vars
        run: |
          echo "HEX_FILE_NAME=$(cd build && ls *.hex)" >> $GITHUB_ENV
          echo "HEX_FILE_PATH=./build/$(cd $(pwd)/build && ls *.hex)" >> $GITHUB_ENV
      

      - name: /[SANITY CHECK/] hex file's name and hex file's path as read from env vars for upload step
        run: |
          echo "${{ env.HEX_FILE_NAME }}"
          echo "${{ env.HEX_FILE_PATH }}"


      - name: upload release artifact
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.HEX_FILE_PATH }}
          asset_name: ${{ env.HEX_FILE_NAME }}
          asset_content_type: application/hex