---
name: Tagged-release

on:
  push:
    tags:
      - 'v*'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & test
        run: |
          echo "done!"

      - uses: "ncipollo/release-action@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "$(pwd)/build/*.hex"